version: '3'

services:
  app:
    image: react-app:latest # Use the image built from Dockerfile
    ports:
      - "3000:80"  # Expose port 80 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
    restart: always